export const brandColors = {
  orange: "#FF7A1A",
  blue: "#0E3A8A",
  primaryAccent: "#14B8A6",
  primaryAccentLight: "#5EEAD4",
  textMain: "#E6F4F1",
  textSecondary: "#9CBAB5",
  textDisabled: "#4F6662",
  statusSuccess: "#73D98B",
  statusWarning: "#F6C453",
  statusError: "#FF6B6B",
} as const;

export const colors = {
  welcome: {
    border: brandColors.primaryAccent,
    accent: brandColors.primaryAccent,
    muted: brandColors.textSecondary,
  },
  releaseNotes: {
    border: brandColors.primaryAccentLight,
    title: brandColors.primaryAccentLight,
    body: brandColors.textSecondary,
  },
  app: {
    title: brandColors.primaryAccentLight,
    meta: brandColors.textSecondary,
    sectionTitle: brandColors.primaryAccentLight,
  },
  event: {
    timestamp: brandColors.textDisabled,
    bracket: brandColors.textSecondary,
    body: brandColors.textMain,
    worker: "#38BDF8",
    supervisor: "#F59E0B",
    system: brandColors.textSecondary,
    hint: brandColors.textDisabled,
    roleFlow: {
      worker: [
        "#0EA5E9",
        "#22D3EE",
        "#67E8F9",
        "#A5F3FC",
        "#67E8F9",
        "#22D3EE",
      ],
      supervisor: [
        "#D97706",
        "#F59E0B",
        "#FBBF24",
        "#FCD34D",
        "#FBBF24",
        "#F59E0B",
      ],
    },
  },
  progress: {
    spinner: brandColors.primaryAccentLight,
    working: brandColors.primaryAccentLight,
    phaseFlow: [
      brandColors.primaryAccent,
      brandColors.primaryAccentLight,
      "#A7F3D0",
      brandColors.primaryAccentLight,
    ],
    supervising: brandColors.statusWarning,
    repairing: brandColors.statusError,
    blocked: brandColors.statusError,
    interrupted: brandColors.statusWarning,
    completed: brandColors.statusSuccess,
    idle: brandColors.textDisabled,
  },
  tool: {
    pending: brandColors.textSecondary,
    completed: brandColors.statusSuccess,
    running: brandColors.textSecondary,
    error: brandColors.statusError,
  },
  command: {
    running: brandColors.textSecondary,
    success: brandColors.statusSuccess,
    error: brandColors.statusError,
  },
  toolCard: {
    pendingBackground: "#282832",
    successBackground: "#283228",
    errorBackground: "#3c2828",
    pendingBorder: "#505050",
    successBorder: "#4b7a57",
    errorBorder: "#8a4f4f",
    title: brandColors.textMain,
    output: brandColors.textSecondary,
    hint: brandColors.textDisabled,
  },
  customMessage: {
    label: brandColors.primaryAccentLight,
    text: brandColors.textMain,
    hint: brandColors.textDisabled,
    success: brandColors.statusSuccess,
    warning: brandColors.statusWarning,
  },
  markdown: {
    heading: brandColors.statusWarning,
    inlineCode: brandColors.primaryAccentLight,
    codeBlock: "#B8F2D8",
    codeBorder: brandColors.textSecondary,
    quote: brandColors.textSecondary,
    quoteBorder: brandColors.textDisabled,
    listBullet: brandColors.primaryAccentLight,
    hr: brandColors.textDisabled,
  },
  userMessage: {
    label: brandColors.textSecondary,
    text: brandColors.textMain,
    background: "#343541",
  },
  plan: {
    pending: brandColors.textSecondary,
    inProgress: brandColors.primaryAccentLight,
    completed: brandColors.statusSuccess,
  },
  input: {
    divider: brandColors.textDisabled,
    prompt: brandColors.textMain,
    hint: brandColors.textSecondary,
  },
  autocomplete: {
    selected: brandColors.primaryAccent,
    muted: brandColors.textDisabled,
    detail: brandColors.textSecondary,
  },
  launcher: {
    hint: brandColors.textSecondary,
    prompt: brandColors.textMain,
    slashSelected: brandColors.primaryAccent,
    slashMuted: brandColors.textDisabled,
    title: brandColors.primaryAccentLight,
  },
  picker: {
    title: brandColors.primaryAccentLight,
    subtitle: brandColors.textSecondary,
    selected: brandColors.primaryAccent,
    text: brandColors.textMain,
    meta: brandColors.textSecondary,
    muted: brandColors.textDisabled,
    hint: brandColors.textSecondary,
  },
  codex: {
    title: brandColors.primaryAccentLight,
    subtitle: brandColors.textSecondary,
    selected: brandColors.primaryAccent,
    current: brandColors.statusSuccess,
    text: brandColors.textMain,
    muted: brandColors.textDisabled,
    hint: brandColors.textSecondary,
    error: brandColors.statusError,
    line: brandColors.textDisabled,
  },
} as const;
